apiVersion: v1
kind: PersistentVolumeClaim #Enough for Develop
metadata:
  name: mssql-claim
spec:
  resources:
    requests:
      storage: 200Mi
#  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany